toolchain: add toolchain for AArch64
phoenix-rtos/phoenix-rtos-build pull request #220
Opened 2024-12-20 11:31 UTC by jmaksymowicz

## Description
Added toolchain for compiling code to AArch64 (Arm in 64-bit mode) and scripts for building Phoenix RTOS for ZynqMP platform.

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (refactoring, style fixes, git/CI config, submodule management, no code logic changes)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [x] Tested by hand on: (list targets here).

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing linter checks and tests passed.
- [x] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [ ] I will merge this PR by myself when appropriate.

2025-01-07 13:22 UTC, badochov requested changes

2025-01-07 13:22 UTC, badochov commented on toolchain/binutils-2.43-04-aarch64-phoenix.patch
> ++	eaarch64phoenix.c \
This entry as well as one in `ld/Makefile.in` are redundant.

THey are only needed if we provide a new linkers configuration (`.sh` files, eg `ld/emulparams/elf32_sparc_phoenix.sh`).

On other platforms we provide those configs even though often times they are redundant. IMHO using the standard config is good enough for now.

2025-01-07 13:22 UTC, badochov commented on toolchain/gcc-9.5.0-12-aarch64-phoenix.patch
> ++aarch64*-*-phoenix*)
What would you say about adding phoenix target to the targets below (`aarch64*-*-elf | aarch64*-*-fuchsia* | aarch64*-*-rtems*)` )?

2025-01-21 14:23 UTC, jmaksymowicz commented on toolchain/gcc-9.5.0-12-aarch64-phoenix.patch
> ++aarch64*-*-phoenix*)
Done.

2025-01-21 14:53 UTC, badochov commented on toolchain/gcc-9.5.0-12-aarch64-phoenix.patch
> ++aarch64*-*-phoenix*)
Ooh I could have worded it better I meant mergin aarch-phoeni to the `arch64*-*-elf | aarch64*-*-fuchsia* | aarch64*-*-rtems*` case

2025-01-28 11:52 UTC, jmaksymowicz commented on toolchain/gcc-9.5.0-12-aarch64-phoenix.patch
> ++aarch64*-*-phoenix*)
OK, done.

2025-01-28 14:34 UTC, badochov approved these changes

2025-02-28 15:15 UTC, jmaksymowicz commented
Can I merge this PR or are there any objections?

2025-03-04 09:41 UTC, merged

2025-03-04 10:34 UTC, nalajcie commented
- this change probably requires changes in the documentation (parts about building toolchain) - maybe can be done later when adding docs about the new architecture supported (but please - don't forget to do it)
- we should probably add the toolchain for new architecture to `phoenix-rtos-docker`?